var new_constants = [
{title: "B.B.K.K.B.K.K.", difficulty: "MAS", constant: "11.8"},
{title: "Reach for the Stars", difficulty: "MAS", constant: "12.3"},
{title: "初音ミクの消失", difficulty: "EXP", constant: "12"},
{title: "初音ミクの消失", difficulty: "MAS", constant: "13.4"},
{title: "コネクト", difficulty: "MAS", constant: "11.5"},
{title: "千本桜", difficulty: "MAS", constant: "11.8"},
{title: "DRAGONLADY", difficulty: "EXP", constant: "11.4"},
{title: "DRAGONLADY", difficulty: "MAS", constant: "13.2"},
{title: "taboo tears you up", difficulty: "MAS", constant: "12.8"},
{title: "ナイト・オブ・ナイツ", difficulty: "MAS", constant: "11.9"},
{title: "一触即発☆禅ガール", difficulty: "MAS", constant: "12.3"},
{title: "ドーナツホール", difficulty: "MAS", constant: "12.7"},
{title: "タイガーランペイジ", difficulty: "MAS", constant: "12.5"},
{title: "Blue Noise", difficulty: "MAS", constant: "13.3"},
{title: "亡國覚醒カタルシス", difficulty: "MAS", constant: "12.2"},
{title: "Lapis", difficulty: "MAS", constant: "12.4"},
{title: "鳥の詩", difficulty: "MAS", constant: "11.3"},
{title: "天ノ弱", difficulty: "MAS", constant: "11.1"},
{title: "sweet little sister", difficulty: "MAS", constant: "11.6"},
{title: "L9", difficulty: "MAS", constant: "12.6"},
{title: "Bad Apple!! feat.nomico", difficulty: "MAS", constant: "11"},
{title: "六兆年と一夜物語", difficulty: "MAS", constant: "12.5"},
{title: "Unlimited Spark!", difficulty: "MAS", constant: "11.8"},
{title: "My First Phone", difficulty: "MAS", constant: "12.8"},
{title: "Cyberozar", difficulty: "EXP", constant: "11.1"},
{title: "Cyberozar", difficulty: "MAS", constant: "13.2"},
{title: "Teriqma", difficulty: "MAS", constant: "12.3"},
{title: "夏祭り", difficulty: "MAS", constant: "11.2"},
{title: "GOLDEN RULE", difficulty: "EXP", constant: "11"},
{title: "GOLDEN RULE", difficulty: "MAS", constant: "13.6"},
{title: "名も無い鳥", difficulty: "MAS", constant: "12.5"},
{title: "Gate of Fate", difficulty: "EXP", constant: "11.7"},
{title: "Gate of Fate", difficulty: "MAS", constant: "13.4"},
{title: "今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", difficulty: "MAS", constant: "12.8"},
{title: "Anemone", difficulty: "MAS", constant: "11.1"},
{title: "明るい未来", difficulty: "MAS", constant: "12.3"},
{title: "昵懇レファレンス", difficulty: "MAS", constant: "11.2"},
{title: "乗り切れ受験ウォーズ", difficulty: "MAS", constant: "11.5"},
{title: "The wheel to the right", difficulty: "EXP", constant: "11.9"},
{title: "The wheel to the right", difficulty: "MAS", constant: "13.4"},
{title: "STAR", difficulty: "MAS", constant: "12.4"},
{title: "Infantoon Fantasy", difficulty: "MAS", constant: "12.4"},
{title: "Genesis", difficulty: "MAS", constant: "13.5"},
{title: "MUSIC PЯAYER", difficulty: "MAS", constant: "12.8"},
{title: "リリーシア", difficulty: "MAS", constant: "11"},
{title: "Counselor", difficulty: "MAS", constant: "11.7"},
{title: "luna blu", difficulty: "EXP", constant: "12"},
{title: "luna blu", difficulty: "MAS", constant: "13.5"},
{title: "ケモノガル", difficulty: "MAS", constant: "12.8"},
{title: "crossing field", difficulty: "MAS", constant: "12.2"},
{title: "ＧＯ！ＧＯ！ラブリズム♥", difficulty: "MAS", constant: ""},
{title: "Memories of Sun and Moon", difficulty: "MAS", constant: "12.5"},
{title: "ロストワンの号哭", difficulty: "MAS", constant: "12.4"},
{title: "The Concept of Love", difficulty: "MAS", constant: "12.3"},
{title: "JET", difficulty: "MAS", constant: "11"},
{title: "L'épisode", difficulty: "EXP", constant: "11.7"},
{title: "L'épisode", difficulty: "MAS", constant: "13.6"},
{title: "Yet Another ”drizzly rain”", difficulty: "MAS", constant: "11.6"},
{title: "最終鬼畜妹・一部声", difficulty: "MAS", constant: "13"},
{title: "蒼空に舞え、墨染の桜", difficulty: "MAS", constant: "12.3"},
{title: "セツナトリップ", difficulty: "MAS", constant: "12.5"},
{title: "砂漠のハンティングガール♡", difficulty: "MAS", constant: "12.1"},
{title: "チルノのパーフェクトさんすう教室", difficulty: "MAS", constant: "11.9"},
{title: "魔理沙は大変なものを盗んでいきました", difficulty: "MAS", constant: "11.8"},
{title: "言ノ葉カルマ", difficulty: "MAS", constant: "12"},
{title: "Tango Rouge", difficulty: "MAS", constant: "13"},
{title: "Tuning Rangers", difficulty: "MAS", constant: "12.5"},
{title: "エンドマークに希望と涙を添えて", difficulty: "EXP", constant: "11.7"},
{title: "エンドマークに希望と涙を添えて", difficulty: "MAS", constant: "13.7"},
{title: "とーきょー全域★アキハバラ？", difficulty: "MAS", constant: "12.5"},
{title: "宛城、炎上！！", difficulty: "EXP", constant: "12.2"},
{title: "宛城、炎上！！", difficulty: "MAS", constant: "13.8"},
{title: "We Gonna Journey", difficulty: "EXP", constant: "11"},
{title: "We Gonna Journey", difficulty: "MAS", constant: "13.1"},
{title: "The ether", difficulty: "MAS", constant: "12.2"},
{title: "ストリーミングハート", difficulty: "MAS", constant: "11.4"},
{title: "Sweet Devil", difficulty: "MAS", constant: "11.9"},
{title: "Dreaming", difficulty: "MAS", constant: "11.7"},
{title: "M.S.S.Planet", difficulty: "MAS", constant: "11.9"},
{title: "腐れ外道とチョコレゐト", difficulty: "MAS", constant: "12.3"},
{title: "アウターサイエンス", difficulty: "MAS", constant: "12.3"},
{title: "四次元跳躍機関", difficulty: "MAS", constant: "12.7"},
{title: "東方妖々夢 ～the maximum moving about～", difficulty: "MAS", constant: "12.7"},
{title: "少女幻葬戦慄曲　～　Necro Fantasia", difficulty: "MAS", constant: "12.7"},
{title: "夏影", difficulty: "MAS", constant: "12.2"},
{title: "The Formula", difficulty: "MAS", constant: "12.7"},
{title: "チルドレンレコード", difficulty: "MAS", constant: "12.7"},
{title: "イカサマライフゲイム", difficulty: "MAS", constant: "12.2"},
{title: "シリョクケンサ", difficulty: "MAS", constant: "11.5"},
{title: "HAELEQUIN (Original Remaster)", difficulty: "EXP", constant: "12.2"},
{title: "HAELEQUIN (Original Remaster)", difficulty: "MAS", constant: "13.8"},
{title: "Vallista", difficulty: "MAS", constant: "13.6"},
{title: "Äventyr", difficulty: "MAS", constant: "12.6"},
{title: "Angel dust", difficulty: "EXP", constant: "11.6"},
{title: "Angel dust", difficulty: "MAS", constant: "13.7"},
{title: "conflict", difficulty: "MAS", constant: "13.3"},
{title: "Guilty", difficulty: "MAS", constant: "11.9"},
{title: "閃鋼のブリューナク", difficulty: "EXP", constant: "11.7"},
{title: "閃鋼のブリューナク", difficulty: "MAS", constant: "13.5"},
{title: "Altale", difficulty: "MAS", constant: "12.7"},
{title: "Aragami", difficulty: "MAS", constant: "13.5"},
{title: "Change Our MIRAI！", difficulty: "MAS", constant: "11.8"},
{title: "夕暮れワンルーム", difficulty: "MAS", constant: "11.7"},
{title: "Theme of SeelischTact", difficulty: "MAS", constant: "11.5"},
{title: "緋色のDance", difficulty: "MAS", constant: "12.2"},
{title: "brilliant better", difficulty: "MAS", constant: "11.8"},
{title: "Alma", difficulty: "MAS", constant: "12.7"},
{title: "Gustav Battle", difficulty: "EXP", constant: "12"},
{title: "Gustav Battle", difficulty: "MAS", constant: "13"},
{title: "SAVIOR OF SONG", difficulty: "MAS", constant: "12.8"},
{title: "FREELY TOMORROW", difficulty: "MAS", constant: "11.4"},
{title: "ギガンティックO.T.N", difficulty: "MAS", constant: "13"},
{title: "フォルテシモBELL", difficulty: "MAS", constant: "11"},
{title: "ジングルベル", difficulty: "MAS", constant: "13.3"},
{title: "言ノ葉遊戯", difficulty: "MAS", constant: "11.6"},
{title: "私の中の幻想的世界観及びその顕現を想起させたある現実での出来事に関する一考察", difficulty: "MAS", constant: "12.5"},
{title: "幾四音-Ixion-", difficulty: "MAS", constant: "11.3"},
{title: "ぼくらの16bit戦争", difficulty: "MAS", constant: "12.8"},
{title: "裏表ラバーズ", difficulty: "MAS", constant: "11.8"},
{title: "脳漿炸裂ガール", difficulty: "MAS", constant: "12.7"},
{title: "ネトゲ廃人シュプレヒコール", difficulty: "MAS", constant: "11.9"},
{title: "elegante", difficulty: "MAS", constant: "11.6"},
{title: "DETARAME ROCK&ROLL THEORY", difficulty: "MAS", constant: "11.2"},
{title: "XL TECHNO", difficulty: "MAS", constant: "12.6"},
{title: "Halcyon", difficulty: "MAS", constant: "13.3"},
{title: "Dance!", difficulty: "MAS", constant: "11.3"},
{title: "Jimang Shot", difficulty: "MAS", constant: "12.7"},
{title: "stella=steLLa", difficulty: "MAS", constant: "12.7"},
{title: "すろぉもぉしょん", difficulty: "MAS", constant: "11.3"},
{title: "怒槌", difficulty: "EXP", constant: "12.7"},
{title: "怒槌", difficulty: "MAS", constant: "14"},
{title: "ってゐ！　～えいえんてゐVer～", difficulty: "MAS", constant: "11.9"},
{title: "患部で止まってすぐ溶ける～狂気の優曇華院", difficulty: "EXP", constant: "11"},
{title: "患部で止まってすぐ溶ける～狂気の優曇華院", difficulty: "MAS", constant: "13.1"},
{title: "ひれ伏せ愚民どもっ！", difficulty: "MAS", constant: "12.7"},
{title: "エテルニタス・ルドロジー", difficulty: "MAS", constant: "12.6"},
{title: "幽闇に目醒めしは", difficulty: "MAS", constant: "11.7"},
{title: "Starlight Vision", difficulty: "MAS", constant: "12.5"},
{title: "Club Ibuki in Break All", difficulty: "MAS", constant: "12.5"},
{title: "Phantasm Brigade", difficulty: "MAS", constant: "13"},
{title: "永遠のメロディ", difficulty: "MAS", constant: "12.3"},
{title: "FREEDOM DiVE", difficulty: "EXP", constant: "11.5"},
{title: "FREEDOM DiVE", difficulty: "MAS", constant: "13.7"},
{title: "Jack-the-Ripper◆", difficulty: "EXP", constant: "11.7"},
{title: "Jack-the-Ripper◆", difficulty: "MAS", constant: "13.1"},
{title: "AVALON", difficulty: "EXP", constant: "11.7"},
{title: "AVALON", difficulty: "MAS", constant: "13.5"},
{title: "ハート・ビート", difficulty: "MAS", constant: "12.1"},
{title: "無敵We are one!!", difficulty: "MAS", constant: "12.1"},
{title: "Contrapasso -inferno-", difficulty: "EXP", constant: "12.1"},
{title: "Contrapasso -inferno-", difficulty: "MAS", constant: "13.9"},
{title: "GEMINI -C-", difficulty: "EXP", constant: "11.2"},
{title: "GEMINI -C-", difficulty: "MAS", constant: "13.2"},
{title: "FLOWER", difficulty: "MAS", constant: "12.3"},
{title: "ちくわパフェだよ☆CKP", difficulty: "MAS", constant: "11.2"},
{title: "SNIPE WHOLE", difficulty: "MAS", constant: "12.7"},
{title: "Signs Of Love (“Never More” ver.)", difficulty: "MAS", constant: "12.2"},
{title: "Your Affection (Daisuke Asakura Remix)", difficulty: "MAS", constant: "11.7"},
{title: "SAMBISTA", difficulty: "MAS", constant: "12.7"},
{title: "アスノヨゾラ哨戒班", difficulty: "MAS", constant: "12.4"},
{title: "天樂", difficulty: "MAS", constant: "12.2"},
{title: "いろは唄", difficulty: "MAS", constant: "12.1"},
{title: "星屑ユートピア", difficulty: "MAS", constant: "11.9"},
{title: "放課後革命", difficulty: "MAS", constant: "12.3"},
{title: "楽園ファンファーレ", difficulty: "MAS", constant: "11.8"},
{title: "サウンドプレイヤー", difficulty: "MAS", constant: "12.4"},
{title: "玩具狂奏曲 -終焉-", difficulty: "EXP", constant: "12.7"},
{title: "玩具狂奏曲 -終焉-", difficulty: "MAS", constant: "14"},
{title: "如月アテンション", difficulty: "MAS", constant: "12.3"},
{title: "Mr. Wonderland", difficulty: "EXP", constant: "11.1"},
{title: "Mr. Wonderland", difficulty: "MAS", constant: "12.9"},
{title: "カミサマネジマキ", difficulty: "EXP", constant: "11"},
{title: "カミサマネジマキ", difficulty: "MAS", constant: "13"},
{title: "恋愛裁判", difficulty: "MAS", constant: "11.4"},
{title: "ウミユリ海底譚", difficulty: "MAS", constant: "12.1"},
{title: "Garakuta Doll Play", difficulty: "EXP", constant: "12.3"},
{title: "Garakuta Doll Play", difficulty: "MAS", constant: "13.8"},
{title: "洗脳", difficulty: "MAS", constant: "11.5"},
{title: "このふざけた素晴らしき世界は、僕の為にある", difficulty: "MAS", constant: "12"},
{title: "紅華刑", difficulty: "EXP", constant: "12"},
{title: "紅華刑", difficulty: "MAS", constant: "13.4"},
{title: "Hyperion", difficulty: "MAS", constant: "12.5"},
{title: "Elemental Creation", difficulty: "EXP", constant: "11.3"},
{title: "Elemental Creation", difficulty: "MAS", constant: "13.5"},
{title: "アルストロメリア", difficulty: "MAS", constant: "12.2"},
{title: "Devastating Blaster", difficulty: "EXP", constant: "12.2"},
{title: "Devastating Blaster", difficulty: "MAS", constant: "13.9"},
{title: "ファッとして桃源郷", difficulty: "MAS", constant: "12.5"},
{title: "フレンズ", difficulty: "MAS", constant: "11.9"},
{title: "夜咄ディセイブ", difficulty: "MAS", constant: "12.6"},
{title: "シュガーソングとビターステップ", difficulty: "MAS", constant: "12.2"},
{title: "回レ！雪月花", difficulty: "MAS", constant: "12.3"},
{title: "Help me, あーりん！", difficulty: "MAS", constant: "11.4"},
{title: "なるとなぎのパーフェクトロックンロール教室", difficulty: "MAS", constant: "12.8"},
{title: "絶世スターゲイト", difficulty: "MAS", constant: "11.7"},
{title: "Schrecklicher Aufstand", difficulty: "EXP", constant: "12.5"},
{title: "Schrecklicher Aufstand", difficulty: "MAS", constant: "13.9"},
{title: "ドライヴ・オン・ザ・レインボー", difficulty: "MAS", constant: "12.7"},
{title: "Philosopher", difficulty: "EXP", constant: "11.8"},
{title: "Philosopher", difficulty: "MAS", constant: "13.5"},
{title: "Crazy ∞ nighT", difficulty: "MAS", constant: "12.5"},
{title: "愛迷エレジー", difficulty: "MAS", constant: "12.3"},
{title: "Warcry", difficulty: "MAS", constant: "13.1"},
{title: "その群青が愛しかったようだった", difficulty: "MAS", constant: "11.7"},
{title: "札付きのワル　～マイケルのうた～", difficulty: "MAS", constant: "12.7"},
{title: "BOKUTO", difficulty: "MAS", constant: "13"},
{title: "TiamaT:F minor", difficulty: "EXP", constant: "12.8"},
{title: "TiamaT:F minor", difficulty: "MAS", constant: "14"},
{title: "Oshama Scramble! (Cranky Remix)", difficulty: "EXP", constant: "11.3"},
{title: "Oshama Scramble! (Cranky Remix)", difficulty: "MAS", constant: "13"},
{title: "D.E.A.D.L.Y.", difficulty: "MAS", constant: "12.4"},
{title: "ロボットプラネットユートピア", difficulty: "MAS", constant: "12.3"},
{title: "Tidal Wave", difficulty: "MAS", constant: "13.5"},
{title: "Hand in Hand", difficulty: "MAS", constant: "11.7"},
{title: "My Dearest Song", difficulty: "MAS", constant: "12.2"},
{title: "猫祭り", difficulty: "MAS", constant: "12.3"},
{title: "ゲシュタルト！テスト期間！！", difficulty: "MAS", constant: "12.7"},
{title: "心象蜃気楼", difficulty: "MAS", constant: "11.5"},
{title: "Bang Babang Bang!!!", difficulty: "MAS", constant: "12.8"},
{title: "僕らの翼", difficulty: "MAS", constant: "11.1"},
{title: "エンヴィキャットウォーク", difficulty: "MAS", constant: "12.4"},
{title: "鬼KYOKAN", difficulty: "MAS", constant: "12.8"},
{title: "有頂天ビバーチェ", difficulty: "MAS", constant: "11.7"},
{title: "ビバハピ", difficulty: "MAS", constant: "11.9"},
{title: "願い星", difficulty: "MAS", constant: "11.6"},
{title: "愛言葉", difficulty: "MAS", constant: "11.5"},
{title: "後夜祭", difficulty: "MAS", constant: "12.3"},
{title: "TRUST", difficulty: "MAS", constant: "12.4"},
{title: "からくりピエロ", difficulty: "MAS", constant: "11.7"},
{title: "深海少女", difficulty: "MAS", constant: "11.7"},
{title: "リモコン", difficulty: "MAS", constant: "11.8"},
{title: "ラクガキスト", difficulty: "EXP", constant: "11.1"},
{title: "ラクガキスト", difficulty: "MAS", constant: "13.4"},
{title: "アカツキアライヴァル", difficulty: "MAS", constant: "11.7"},
{title: "神曲", difficulty: "MAS", constant: "12"},
{title: "幸せになれる隠しコマンドがあるらしい", difficulty: "MAS", constant: "12.7"},
{title: "Tell Your World", difficulty: "MAS", constant: "11.5"},
{title: "ロミオとシンデレラ", difficulty: "MAS", constant: "11.9"},
{title: "First Twinkle", difficulty: "MAS", constant: "11.6"},
{title: "ウソラセラ", difficulty: "MAS", constant: "12.6"},
{title: "檄!帝国華撃団", difficulty: "MAS", constant: "11.3"},
{title: "Kronos", difficulty: "MAS", constant: "12.4"},
{title: "月に叢雲華に風", difficulty: "MAS", constant: "12.1"},
{title: "インビジブル", difficulty: "MAS", constant: "13.2"},
{title: "人生リセットボタン", difficulty: "MAS", constant: "12.8"},
{title: "響", difficulty: "MAS", constant: "12"},
{title: "かくしん的☆めたまるふぉ～ぜっ!", difficulty: "MAS", constant: "12.1"},
{title: "風仁雷仁", difficulty: "MAS", constant: "12.3"},
{title: "PRIVATE SERVICE", difficulty: "MAS", constant: "12.6"},
{title: "secret base ～君がくれたもの～ (10 years after Ver.)", difficulty: "MAS", constant: ""},
{title: "No Routine", difficulty: "MAS", constant: "12.2"},
{title: "白い雪のプリンセスは", difficulty: "MAS", constant: "12.2"},
{title: "Strahv", difficulty: "EXP", constant: "11"},
{title: "Strahv", difficulty: "MAS", constant: "13.3"},
{title: "In The Blue Sky '01", difficulty: "MAS", constant: "11.7"},
{title: "幻想のサテライト", difficulty: "EXP", constant: "11"},
{title: "幻想のサテライト", difficulty: "MAS", constant: "13.1"},
{title: "凛として咲く花の如く", difficulty: "MAS", constant: "12.2"},
{title: "Paqqin", difficulty: "MAS", constant: "12.7"},
{title: "fake!fake!", difficulty: "MAS", constant: "11.9"},
{title: "Rising Hope", difficulty: "MAS", constant: "12.5"},
{title: "覚醒楽奏メタフィクション", difficulty: "EXP", constant: "11.2"},
{title: "覚醒楽奏メタフィクション", difficulty: "MAS", constant: "13.3"},
{title: "Be My Friend", difficulty: "MAS", constant: "11.8"},
{title: "ぶいえす!!らいばる!!", difficulty: "EXP", constant: "11"},
{title: "ぶいえす!!らいばる!!", difficulty: "MAS", constant: "13.2"},
{title: "ひだまりデイズ", difficulty: "MAS", constant: "11.4"},
{title: "This game", difficulty: "MAS", constant: "11.8"},
{title: "オラシオン", difficulty: "MAS", constant: "11.3"},
{title: "みくみくにしてあげる♪【してやんよ】", difficulty: "MAS", constant: "11.5"},
{title: "Air", difficulty: "MAS", constant: "13.4"},
{title: "DataErr0r", difficulty: "MAS", constant: "13"},
{title: "Say A Vengeance", difficulty: "MAS", constant: "12.7"},
{title: "010", difficulty: "MAS", constant: "12.6"},
{title: "ERIS -Legend of Gaidelia-", difficulty: "MAS", constant: "12.5"},
{title: "Imperishable Night 2006 (2016 Refine)", difficulty: "EXP", constant: "11"},
{title: "Imperishable Night 2006 (2016 Refine)", difficulty: "MAS", constant: "13.6"},
{title: "Dreadnought", difficulty: "MAS", constant: "13.6"},
{title: "STAGER", difficulty: "MAS", constant: "12.6"},
{title: "Her Majesty", difficulty: "MAS", constant: "12.6"},
{title: "Sakura Fubuki", difficulty: "MAS", constant: "12.5"},
{title: "JULIAN", difficulty: "MAS", constant: "12.7"},
{title: "★LittlE HearTs★", difficulty: "EXP", constant: "11.4"},
{title: "★LittlE HearTs★", difficulty: "MAS", constant: "13.8"},
{title: "STAIRWAY TO GENERATION", difficulty: "MAS", constant: "12.3"},
{title: "ドキドキDREAM!!!", difficulty: "MAS", constant: "12.1"},
{title: "猛進ソリストライフ！", difficulty: "MAS", constant: "12.2"},
{title: "空威張りビヘイビア", difficulty: "MAS", constant: "12.3"},
{title: "FLOATED CALM", difficulty: "MAS", constant: "12.4"},
{title: "Supersonic Generation", difficulty: "EXP", constant: "11.2"},
{title: "Supersonic Generation", difficulty: "MAS", constant: "13.4"},
{title: "シジョウノコエ VOCALO ver.", difficulty: "MAS", constant: "12.2"},
{title: "Tic Tac DREAMIN’", difficulty: "MAS", constant: ""},
{title: "SPICY SWINGY STYLE", difficulty: "MAS", constant: "12.3"},
{title: "RevolutionGame", difficulty: "MAS", constant: "11.7"},
{title: "Still", difficulty: "MAS", constant: "12.5"},
{title: "おまかせ！！トラブルメイ娘☆とれびちゃん", difficulty: "MAS", constant: "13.1"},
{title: "オススメ☆♂♀☆でぃすとぴあ", difficulty: "MAS", constant: "13.4"},
{title: "Daydream café", difficulty: "MAS", constant: "11.6"},
{title: "ノーポイッ!", difficulty: "MAS", constant: "11.8"},
{title: "ムーンライト伝説", difficulty: "MAS", constant: "11.7"},
{title: "Jumping!!", difficulty: "MAS", constant: "11.3"},
{title: "FEEL×ALIVE", difficulty: "MAS", constant: "12.7"},
{title: "ぶぉん！ぶぉん！らいど・おん！", difficulty: "MAS", constant: "12.9"},
{title: "Star☆Glitter", difficulty: "MAS", constant: "12"},
{title: "ラブリー☆えんじぇる!!", difficulty: "MAS", constant: "12.3"},
{title: "クローバー♣かくめーしょん", difficulty: "MAS", constant: "12.3"},
{title: "ぐーちょきパレード", difficulty: "MAS", constant: "11.7"},
{title: "My Soul,Your Beats!", difficulty: "MAS", constant: "11.7"},
{title: "Thousand Enemies", difficulty: "MAS", constant: "11.8"},
{title: "夢想歌", difficulty: "MAS", constant: "11.3"},
{title: "Face of Fact", difficulty: "MAS", constant: "12.1"},
{title: "true my heart -Lovable mix-", difficulty: "MAS", constant: "11.6"},
{title: "いーあるふぁんくらぶ", difficulty: "MAS", constant: "11.4"},
{title: "おこちゃま戦争", difficulty: "MAS", constant: "12.8"},
{title: "エイリアンエイリアン", difficulty: "MAS", constant: "11.7"},
{title: "虎視眈々", difficulty: "MAS", constant: "12.4"},
{title: "アンハッピーリフレイン", difficulty: "MAS", constant: "12.7"},
{title: "すきなことだけでいいです", difficulty: "MAS", constant: "12.2"},
{title: "デリヘル呼んだら君が来た", difficulty: "MAS", constant: "12.4"},
{title: "チュルリラ・チュルリラ・ダッダッダ！", difficulty: "MAS", constant: "12.6"},
{title: "だんだん早くなる", difficulty: "MAS", constant: "11.5"},
{title: "ECHO", difficulty: "MAS", constant: "12.2"},
{title: "泡沫、哀のまほろば", difficulty: "MAS", constant: "11.5"},
{title: "愛き夜道 feat. ランコ、雨天決行", difficulty: "MAS", constant: "12"},
{title: "Starlight Dance Floor", difficulty: "MAS", constant: "11.4"},
{title: "Witches night", difficulty: "MAS", constant: "12"},
{title: "Help me, ERINNNNNN!! -Cranky remix-", difficulty: "MAS", constant: "12.2"},
{title: "仙酌絶唱のファンタジア", difficulty: "MAS", constant: "12.6"},
{title: "キュアリアス光吉古牌　－祭－", difficulty: "MAS", constant: "12.4"},
{title: "Evans", difficulty: "MAS", constant: "13.4"},
{title: "神威", difficulty: "EXP", constant: "12.7"},
{title: "神威", difficulty: "MAS", constant: "13.9"},
{title: "GOODTEK", difficulty: "MAS", constant: "13.3"},
{title: "Name of oath", difficulty: "EXP", constant: "11"},
{title: "Name of oath", difficulty: "MAS", constant: "13.5"},
{title: "Bird Sprite", difficulty: "MAS", constant: "12.2"},
{title: "オモイヨシノ", difficulty: "MAS", constant: "11.5"},
{title: "Dengeki Tube", difficulty: "EXP", constant: "11.7"},
{title: "Dengeki Tube", difficulty: "MAS", constant: "13.9"},
{title: "若い力 -SEGA HARD GIRLS MIX-", difficulty: "MAS", constant: "11.7"},
{title: "レッツゴー!陰陽師", difficulty: "MAS", constant: "11.9"},
{title: "あねぺったん", difficulty: "MAS", constant: "12.1"},
{title: "Like the Wind [Reborn]", difficulty: "EXP", constant: "11"},
{title: "Like the Wind [Reborn]", difficulty: "MAS", constant: "13.5"},
{title: "天国と地獄 -言ノ葉リンネ-", difficulty: "MAS", constant: "11.8"},
{title: "最愛テトラグラマトン", difficulty: "MAS", constant: "12.6"},
{title: "悪戯", difficulty: "MAS", constant: "12.2"},
{title: "りばーぶ", difficulty: "MAS", constant: "11.2"},
{title: "Barbed Eye", difficulty: "MAS", constant: "12"},
{title: "分からない", difficulty: "MAS", constant: "13.2"},
{title: "相思創愛", difficulty: "MAS", constant: "12.4"},
{title: "混沌を越えし我らが神聖なる調律主を讃えよ", difficulty: "EXP", constant: "13.2"},
{title: "混沌を越えし我らが神聖なる調律主を讃えよ", difficulty: "MAS", constant: "14.1"},
{title: "Finite", difficulty: "MAS", constant: "13.9"},
{title: "MY LIBERATION", difficulty: "MAS", constant: "12.7"},
{title: "地球最後の告白を", difficulty: "MAS", constant: "12.3"},
{title: "The wheel to the Night ～インド人が夢に!?～", difficulty: "MAS", constant: "13"},
{title: "We Gonna Party -Feline Groove Mix-", difficulty: "EXP", constant: "11.3"},
{title: "We Gonna Party -Feline Groove Mix-", difficulty: "MAS", constant: "13.3"},
{title: "Through The Tower", difficulty: "MAS", constant: "12.4"},
{title: "Redo", difficulty: "MAS", constant: "12.4"},
{title: "SAKURAスキップ", difficulty: "MAS", constant: "11.7"},
{title: "Now Loading!!!!", difficulty: "MAS", constant: "12.3"},
{title: "前前前世", difficulty: "MAS", constant: "11.9"},
{title: "MEMORIA", difficulty: "MAS", constant: "11.6"},
{title: "MIRU key way", difficulty: "MAS", constant: "11.6"},
{title: "華鳥風月", difficulty: "MAS", constant: "11.5"},
{title: "儚きもの人間", difficulty: "MAS", constant: "12.5"},
{title: "ＧＯ！ＧＯ！ラブリズム♥ ～あーりん書類審査通過記念Ver.～", difficulty: "MAS", constant: "12.1"},
{title: "Session High⤴", difficulty: "MAS", constant: "12.6"},
{title: "光線チューニング", difficulty: "MAS", constant: "12.3"},
{title: "立川浄穢捕物帳", difficulty: "MAS", constant: "13"},
{title: "眠れぬ夜君を想フ", difficulty: "MAS", constant: "13.3"},
{title: "JIGOKU STATION CENTRAL GATE", difficulty: "EXP", constant: "11.4"},
{title: "JIGOKU STATION CENTRAL GATE", difficulty: "MAS", constant: "13.3"},
{title: "PinqPiq", difficulty: "MAS", constant: "12.5"},
{title: "トリスメギストス", difficulty: "MAS", constant: "13.2"},
{title: "WE GOTTA SOUL", difficulty: "MAS", constant: "12.2"},
{title: "哀しみ集め", difficulty: "MAS", constant: "12"},
{title: "キラメケ→Shoot it Now!", difficulty: "MAS", constant: "12.9"},
{title: "Kattobi KEIKYU Rider", difficulty: "EXP", constant: "12.5"},
{title: "Kattobi KEIKYU Rider", difficulty: "MAS", constant: "13.8"},
{title: "Glorious Crown (tpz over-Over-OVERCUTE REMIX)", difficulty: "EXP", constant: "12.6"},
{title: "Glorious Crown (tpz over-Over-OVERCUTE REMIX)", difficulty: "MAS", constant: "13.9"},
{title: "エレクトロサチュレイタ", difficulty: "MAS", constant: "11.7"},
{title: "Palette", difficulty: "MAS", constant: "12.1"},
{title: "アマツキツネ", difficulty: "MAS", constant: "11.8"},
{title: "パーフェクト生命", difficulty: "MAS", constant: "12.7"},
{title: "のぼれ！すすめ！高い塔", difficulty: "MAS", constant: "13.3"},
{title: "害虫", difficulty: "MAS", constant: "13.2"},
{title: "ガチャガチャきゅ～と・ふぃぎゅ@メイト", difficulty: "MAS", constant: "12.5"},
{title: "Vampire", difficulty: "MAS", constant: "12.6"},
{title: "ケロ⑨destiny", difficulty: "MAS", constant: "12.7"},
{title: "Last Moments", difficulty: "MAS", constant: "12.5"},
{title: "風に乗せた願い", difficulty: "MAS", constant: "12.8"},
{title: "天狗の落とし文 feat. ｙｔｒ", difficulty: "MAS", constant: "12.4"},
{title: "物凄い勢いでけーねが物凄いうた", difficulty: "MAS", constant: "12.2"},
{title: "Wake up Dreamer", difficulty: "MAS", constant: "12.6"},
{title: "World Vanquisher", difficulty: "EXP", constant: "12.7"},
{title: "World Vanquisher", difficulty: "MAS", constant: "14.1"},
{title: "macrocosmos", difficulty: "EXP", constant: "12.5"},
{title: "macrocosmos", difficulty: "MAS", constant: "14"},
{title: "Iudicium", difficulty: "EXP", constant: "11.9"},
{title: "Iudicium", difficulty: "MAS", constant: "13.7"},
{title: "Twice up Scenery", difficulty: "MAS", constant: "13.2"},
{title: "奏者はただ背中と提琴で語るのみ", difficulty: "MAS", constant: "12.9"},
{title: "Xevel", difficulty: "EXP", constant: "12"},
{title: "Xevel", difficulty: "MAS", constant: "13.9"},
{title: "セイクリッド　ルイン", difficulty: "EXP", constant: "11.4"},
{title: "セイクリッド　ルイン", difficulty: "MAS", constant: "13.5"},
{title: "極圏", difficulty: "EXP", constant: "11.7"},
{title: "極圏", difficulty: "MAS", constant: "13.6"},
{title: "Scarlet Lance", difficulty: "EXP", constant: "11.9"},
{title: "Scarlet Lance", difficulty: "MAS", constant: "13.6"},
{title: "DreamRiser", difficulty: "MAS", constant: "11.5"},
{title: "ホシトハナ", difficulty: "MAS", constant: "11.6"},
{title: "Just Be Friends", difficulty: "MAS", constant: "11.7"},
{title: "炉心融解", difficulty: "MAS", constant: "11.9"},
{title: "Fire◎Flower", difficulty: "MAS", constant: "12.4"},
{title: "卑怯戦隊うろたんだー", difficulty: "MAS", constant: "12.3"},
{title: "イロトリドリのメロディ", difficulty: "MAS", constant: "12.5"},
{title: "セハガガガンバッちゃう！！", difficulty: "MAS", constant: "12.6"},
{title: "Burning Hearts ～炎のANGEL～", difficulty: "MAS", constant: "12.5"},
{title: "Our Fighting", difficulty: "MAS", constant: "11.8"},
{title: "VERTeX", difficulty: "EXP", constant: "11.9"},
{title: "VERTeX", difficulty: "MAS", constant: "13.7"},
{title: "-OutsideR:RequieM-", difficulty: "MAS", constant: "12.7"},
{title: "夢と夢～あの日のメロディ～", difficulty: "MAS", constant: "11.3"},
{title: "La Baguette Magique", difficulty: "MAS", constant: "12.5"},
{title: "bubble attack", difficulty: "MAS", constant: "12.9"},
{title: "The Darkness of Valhalla", difficulty: "MAS", constant: "12.5"},
{title: "時の冒険者", difficulty: "MAS", constant: "12.7"},
{title: "Rendezvous", difficulty: "MAS", constant: "12.5"},
{title: "EXECUTOR", difficulty: "MAS", constant: "12.7"},
{title: "不安定な神様", difficulty: "MAS", constant: "12.1"},
{title: "Hyper Active", difficulty: "MAS", constant: "13.3"},
{title: "L'épilogue", difficulty: "MAS", constant: "12.5"},
{title: "D✪N’T ST✪P R✪CKIN’ ～[✪_✪] MIX～", difficulty: "MAS", constant: "12.5"},
{title: "Caliburne ～Story of the Legendary sword～", difficulty: "EXP", constant: "12.1"},
{title: "Caliburne ～Story of the Legendary sword～", difficulty: "MAS", constant: "13.9"},
{title: "プリズム", difficulty: "MAS", constant: "11.7"},
{title: "星灯", difficulty: "MAS", constant: "11.5"},
{title: "Clover Heart's", difficulty: "MAS", constant: "11.8"},
{title: "スイートマジック", difficulty: "MAS", constant: "11.8"},
{title: "Calamity Fortune", difficulty: "EXP", constant: "11.5"},
{title: "Calamity Fortune", difficulty: "MAS", constant: "13.7"},
{title: "Melody！", difficulty: "MAS", constant: "11.9"},
{title: "G e n g a o z o", difficulty: "EXP", constant: "12.4"},
{title: "G e n g a o z o", difficulty: "MAS", constant: "13.6"},
{title: "Vitalization", difficulty: "MAS", constant: "12.1"},
{title: "フラジール", difficulty: "MAS", constant: "11.6"},
{title: "Absolunote", difficulty: "MAS", constant: "12.3"},
{title: "木彫り鯰と右肩ゾンビ", difficulty: "MAS", constant: "12.4"},
{title: "ヒビカセ", difficulty: "MAS", constant: "12.5"},
{title: "WAVE", difficulty: "MAS", constant: "12.2"},
{title: "Philosophyz", difficulty: "MAS", constant: "11.9"},
{title: "虹色のフリューゲル", difficulty: "MAS", constant: "11.8"},
{title: "ETERNAL DRAIN", difficulty: "MAS", constant: "12.6"},
{title: "Paradisus-Paradoxum", difficulty: "MAS", constant: "12.4"},
{title: "ようこそジャパリパークへ", difficulty: "MAS", constant: "12.1"},
{title: "チルノのパーフェクトさんすう教室　⑨周年バージョン", difficulty: "MAS", constant: "12.9"},
{title: "プレパレード", difficulty: "MAS", constant: "11.8"},
{title: "オレンジ", difficulty: "MAS", constant: "11.5"},
{title: "Cosmic twinkle star", difficulty: "MAS", constant: "12.4"},
{title: "終わりなき物語", difficulty: "MAS", constant: "12.3"},
{title: "BlazinG AIR", difficulty: "MAS", constant: "13.3"},
{title: "Change me", difficulty: "MAS", constant: "12.5"},
{title: "ハレ晴レユカイ", difficulty: "MAS", constant: "12"},
{title: "AMAZING MIGHTYYYY!!!!", difficulty: "EXP", constant: "12"},
{title: "AMAZING MIGHTYYYY!!!!", difficulty: "MAS", constant: "13.8"},
{title: "砂の惑星 feat. HATSUNE MIKU", difficulty: "MAS", constant: "12.3"},
{title: "ヒトリゴト", difficulty: "MAS", constant: "11.7"},
{title: "adrenaline!!!", difficulty: "MAS", constant: "11.7"},
{title: "夢路らびりんす", difficulty: "MAS", constant: "11.7"},
{title: "全力バタンキュー", difficulty: "MAS", constant: "11.4"},
{title: "Last Proof", difficulty: "MAS", constant: "12.4"},
{title: "拝啓ドッペルゲンガー", difficulty: "MAS", constant: "13.1"},
{title: "Doppelganger", difficulty: "EXP", constant: "11.8"},
{title: "Doppelganger", difficulty: "MAS", constant: "13.8"},
{title: "色は匂へど散りぬるを", difficulty: "MAS", constant: "11.2"},
{title: "ポルカドット", difficulty: "MAS", constant: "11.3"},
{title: "Sparking Revolver", difficulty: "EXP", constant: "11.4"},
{title: "Sparking Revolver", difficulty: "MAS", constant: "13.6"},
{title: "Gate of Doom", difficulty: "EXP", constant: "12"},
{title: "Gate of Doom", difficulty: "MAS", constant: "13.8"},
{title: "ダンスロボットダンス", difficulty: "MAS", constant: "12.4"},
{title: "アルカリレットウセイ", difficulty: "MAS", constant: "11.6"},
{title: "キレキャリオン", difficulty: "MAS", constant: "12.3"},
{title: "グラーヴェ", difficulty: "MAS", constant: "12"},
{title: "レトロマニア狂想曲", difficulty: "MAS", constant: "12.5"},
{title: "イロドリミドリ杯花映塚全一決定戦公式テーマソング『ウソテイ』", difficulty: "MAS", constant: "12.3"},
{title: "otorii INNOVATED -[i]3-", difficulty: "EXP", constant: "12.6"},
{title: "otorii INNOVATED -[i]3-", difficulty: "MAS", constant: "13.9"},
{title: "未来イマジネーション！", difficulty: "MAS", constant: "11.9"},
{title: "純情-SAKURA-", difficulty: "MAS", constant: "12.5"},
{title: "青春サイダー", difficulty: "MAS", constant: "12.5"},
{title: "Very! Merry!! Session!!!", difficulty: "MAS", constant: "12.3"},
{title: "popcorn", difficulty: "MAS", constant: "11.9"},
{title: "Pastel Party", difficulty: "MAS", constant: "12.9"},
{title: "はちみつアドベンチャー", difficulty: "MAS", constant: "12.4"},
{title: "CHOCOLATE BOMB!!!!", difficulty: "MAS", constant: "13.3"},
{title: "Twilight", difficulty: "EXP", constant: "11.3"},
{title: "Twilight", difficulty: "MAS", constant: "13.5"},
{title: "ねぇ、壊れタ人形ハ何処へ棄テらレるノ？", difficulty: "EXP", constant: "12.4"},
{title: "ねぇ、壊れタ人形ハ何処へ棄テらレるノ？", difficulty: "MAS", constant: "13.8"},
{title: "WARNING×WARNING×WARNING", difficulty: "MAS", constant: "12.4"},
{title: "Grip & Break down !!", difficulty: "MAS", constant: "12.3"},
{title: "ネ！コ！", difficulty: "MAS", constant: "12"},
{title: "マトリョシカ", difficulty: "MAS", constant: "12.2"},
{title: "ゴーゴー幽霊船", difficulty: "MAS", constant: "12.5"},
{title: "La Flesvelka", difficulty: "MAS", constant: "12.5"},
{title: "羽ばたきのバースデイ", difficulty: "MAS", constant: "11.9"},
{title: "楔", difficulty: "MAS", constant: "12.4"},
{title: "Los! Los! Los!", difficulty: "MAS", constant: "12.3"},
{title: "Uncontrollable", difficulty: "MAS", constant: "12.4"},
{title: "碧き孤島のアングゥィス", difficulty: "MAS", constant: "12.8"},
{title: "ラブって♡ジュエリー♪えんじぇる☆ブレイク！！", difficulty: "MAS", constant: "12.6"},
{title: "ぶれいくるみるくらぶ！", difficulty: "MAS", constant: "12.4"},
{title: "クレッシェンド・ストーリー", difficulty: "MAS", constant: "12.4"},
{title: "Sentimental Snow", difficulty: "MAS", constant: "11.5"},
{title: "サンシャインサマー☆夏期講習", difficulty: "MAS", constant: "12.9"},
{title: "NYAN-NYA, More! ラブシャイン、Chu♥", difficulty: "MAS", constant: "12.6"},
{title: "ガヴリールドロップキック", difficulty: "MAS", constant: "12.1"},
{title: "厨病激発ボーイ", difficulty: "MAS", constant: "12.5"},
{title: "StargazeR", difficulty: "MAS", constant: "12.2"},
{title: "ゴーストルール", difficulty: "MAS", constant: "12.7"},
{title: "頓珍漢の宴", difficulty: "MAS", constant: "13"},
{title: "TOMORROW", difficulty: "MAS", constant: "11.6"},
{title: "Chocolate Happy", difficulty: "MAS", constant: "11.1"},
{title: "管弦楽組曲 第3番 ニ長調「第2曲（G線上のアリア）」BWV.1068-2", difficulty: "EXP", constant: ""},
{title: "管弦楽組曲 第3番 ニ長調「第2曲（G線上のアリア）」BWV.1068-2", difficulty: "MAS", constant: "13.5"},
{title: "ここで一席！　Oshama Scramble!", difficulty: "MAS", constant: "12.5"},
{title: "Scream out! -CHUNITHM Tuning-", difficulty: "MAS", constant: "12.4"},
{title: "Spring of Dreams", difficulty: "MAS", constant: "12.2"},
{title: "Floating Darkness", difficulty: "MAS", constant: "12.7"},
{title: "あ・え・い・う・え・お・あお!!", difficulty: "MAS", constant: "12.4"},
{title: "かーてんこーる!!!!!", difficulty: "MAS", constant: "11.9"},
{title: "SEVENTH HAVEN", difficulty: "MAS", constant: "12.1"},
{title: "Bravely You", difficulty: "MAS", constant: "11.6"},
{title: "Link with U", difficulty: "MAS", constant: "11.7"},
{title: "Change Our MIRAI！ (Our 7 Lights)", difficulty: "MAS", constant: "12.5"},
{title: "Dual Fractal", difficulty: "MAS", constant: "12.8"},
{title: "Drivessover", difficulty: "EXP", constant: "11.3"},
{title: "Drivessover", difficulty: "MAS", constant: "12.8"},
{title: "Surveiller et punir", difficulty: "EXP", constant: "11.9"},
{title: "Surveiller et punir", difficulty: "MAS", constant: "13.9"},
{title: "業 -善なる神とこの世の悪について-", difficulty: "EXP", constant: "13"},
{title: "業 -善なる神とこの世の悪について-", difficulty: "MAS", constant: "14.1"},
{title: "メニメニマニマニ", difficulty: "MAS", constant: "12.3"},
{title: "ニホンゴワカリマセン", difficulty: "MAS", constant: "11.6"},
{title: "Get goal!", difficulty: "MAS", constant: "11.4"},
{title: "Rolling Rolling!", difficulty: "MAS", constant: "11.9"},
{title: "灼熱スイッチ", difficulty: "MAS", constant: "12.1"},
{title: "volcanic", difficulty: "EXP", constant: "12.4"},
{title: "volcanic", difficulty: "MAS", constant: "13.5"},
{title: "アンノウン・マザーグース", difficulty: "MAS", constant: "12.6"},
{title: "ゆけむり魂温泉 II", difficulty: "MAS", constant: "12.2"},
{title: "サドマミホリック", difficulty: "MAS", constant: "13.2"},
{title: "Candyland Symphony", difficulty: "MAS", constant: "12.4"},
{title: "初音ミクの激唱", difficulty: "EXP", constant: "12.4"},
{title: "初音ミクの激唱", difficulty: "MAS", constant: "13.7"},
{title: "つるぺったん", difficulty: "MAS", constant: "12.4"},
{title: "咲キ誇レ常世ノ華", difficulty: "MAS", constant: "12.4"},
{title: "チルノおかんのさいきょう☆バイブスごはん", difficulty: "MAS", constant: "12.6"},
{title: "放課後ストライド", difficulty: "MAS", constant: "12.1"},
{title: "きゅうりバーにダイブ", difficulty: "MAS", constant: "13.4"},
{title: "sister's noise", difficulty: "MAS", constant: "11.5"},
